version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '8080:80'
    volumes:
      - ./www/:/var/www/html
      - ./phpmyadmin/:/var/www/html/phpmyadmin
    links: 
      - mysql
    depends_on:
      - mysql
volumes:
  db:
